/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-tertiary": "#ffffff",
          "surface-variant": "#e0e2e6",
          "tertiary-container": "#2c3646",
          "secondary-container": "#fed000",
          "on-surface": "#191c1f",
          "inverse-on-surface": "#eff1f5",
          "surface-tint": "#465f88",
          "on-secondary": "#ffffff",
          "on-secondary-fixed-variant": "#564500",
          "surface-container-highest": "#e0e2e6",
          "tertiary-fixed-dim": "#bdc7db",
          "surface-container-high": "#e6e8ec",
          "error-container": "#ffdad6",
          "primary-fixed": "#d6e3ff",
          "outline": "#74777f",
          "on-tertiary-container": "#959fb2",
          "on-tertiary-fixed-variant": "#3d4757",
          "on-primary-container": "#87a0cd",
          "on-secondary-container": "#6f5900",
          "surface-container-lowest": "#ffffff",
          "surface-dim": "#d8dade",
          "error": "#ba1a1a",
          "on-surface-variant": "#44474e",
          "surface-bright": "#f7f9fd",
          "outline-variant": "#c4c6cf",
          "on-tertiary-fixed": "#121c2a",
          "on-primary-fixed-variant": "#2e476f",
          "primary-container": "#1b365d",
          "on-primary-fixed": "#001b3d",
          "secondary-fixed-dim": "#edc200",
          "on-primary": "#ffffff",
          "tertiary": "#17212f",
          "primary-fixed-dim": "#aec7f7",
          "primary": "#002046",
          "surface-container": "#eceef2",
          "background": "#f7f9fd",
          "tertiary-fixed": "#d9e3f7",
          "secondary": "#725c00",
          "inverse-primary": "#aec7f7",
          "secondary-fixed": "#ffe07f",
          "surface-container-low": "#f2f4f8",
          "on-error": "#ffffff",
          "inverse-surface": "#2d3134",
          "on-background": "#191c1f",
          "on-secondary-fixed": "#231b00",
          "surface": "#f7f9fd",
          "on-error-container": "#93000a"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "lg": "24px",
          "grid-margin": "64px",
          "md": "16px",
          "xl": "48px",
          "sm": "8px",
          "grid-gutter": "24px",
          "unit": "4px",
          "xs": "4px"
      },
      "fontFamily": {
          "h3": ["Inter", "sans-serif"],
          "h1": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "ui-button": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "h2": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
          "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
          "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "ui-button": ["14px", {"lineHeight": "1.0", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
